---
title: "stats"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(tidyverse)


```

```{r}
data = read.csv('../melanoma.csv')
summary(data)
```

```{r}
par(mfcol = c(1,3))
boxplot(data$age, main = "Age",col='cadetblue3')
boxplot(data$thickness, main = "Thickness",col='cadetblue1')
barplot(table(data$ulcer), main = "Ulcer",col='cadetblue2')
```

```{r}
# regression and correlation time~thickness
lm_time_thickness<-lm(time~thickness,data=data)
summary(lm_time_thickness)
```

```{r}
cor.test(data$time,data$thickness,method='spearman',exact=FALSE)
```

```{r}
scatter.smooth(df$time,df$thickness,
              main="Scatter Plot for Time and Thickness",
              xlab="Time",
              ylab="Thickness",
              col='firebrick')
```

```{r}
# regression and correlation time~age
lm_time_age<-lm(time~age,data=data)
summary(lm_time_age)
```

```{r}
cor.test(data$time,data$age,method='spearman',
         exact=FALSE)
```

```{r}
scatter.smooth(df$time,df$age,main="Scatter Plot for Time and Age",
                xlab="Time",
              ylab="Age",
              col='firebrick1')
```

```{r}
cor.test(data$thickness,data$age,method='spearman',
         exact=FALSE)
```

```{r}
# regression and correlation thickness~age
lm_time_age<-lm(thickness~age,data=data)
summary(lm_time_age)
```

```{r}
scatter.smooth(df$thickness,df$age,
               main="Scatter Plot for Thickness and Age",
                xlab="Thickness",
              ylab="Age",
              col='firebrick2')
```

```{r}
male_data=data[data$sex %in% c(1),]
female_data =data[data$sex %in% c(0),]
```

```{r}
#time 
col <- 'time'
t.test(male_data[col],female_data[col])
```

```{r}
col <- 'thickness'
t.test(male_data[col],female_data[col])
```

```{r}
col <- 'age'
t.test(male_data[col],female_data[col])
```

```{r}
cor.test(male_data$age,female_data$age)
#male_data$time
```

```{r}
#time 

qqplot(male_data$time,female_data$time,main="QQ-plots for time",xlab = 'Male',ylab='Female',
       col='blue')
```

```{r}
#thickness

qqplot(male_data$thickness,female_data$thickness,main="QQ-plots for thickness",xlab = 'Male',ylab='Female',
       col='blue')
```

```{r}
#age

qqplot(male_data$age,female_data$age,main="QQ-plots for age",xlab = 'Male',ylab='Female',
       col='blue')
```

